name: Swift CI

on:
  push:
    branches: [ "main", "dev", "qa" ]
  pull_request:
    branches: [ "main", "dev", "qa", "feature/*", "release/*" ]

env:
  XCODE_VERSION: '16.1'
  PROJECT_NAME: 'build-test-ios'
  SCHEME_NAME: 'build-test-ios'

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache SwiftLint
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/swiftlint
          key: swiftlint-${{ runner.os }}
          
      - name: Install SwiftLint
        run: |
          if ! command -v swiftlint &> /dev/null; then
            brew install swiftlint
          fi
          
      - name: Run SwiftLint
        run: |
         swiftlint lint --reporter github-actions-logging --reporter json > swiftlint-report.json || true
          
      - name: Upload SwiftLint Results
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: swiftlint-results
          path: swiftlint-report.json

  test:
    needs: [lint]
    runs-on: macos-latest
    strategy:
      matrix:
        destination: 
          - "platform=iOS Simulator,name=iPhone 16,OS=18.1"
          - "platform=iOS Simulator,name=iPhone 16 Plus,OS=18.1" 
          - "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1"
          - "platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.1"
          
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
          
      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
         path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
         key: ${{ runner.os }}-spm-${{ hashFiles('**/*.xcodeproj', '**/Package.swift') }}
            
      - name: Build and Test
        run: |
          set -o pipefail
          xcodebuild test \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -destination "${{ matrix.destination }}" \
            -resultBundlePath TestResults-${{ strategy.job-index }} \
            -enableCodeCoverage YES \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            | xcpretty --report junit --output test-results.xml
            
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
           name: build-artifacts-${{ matrix.configuration }}
           path: |
               ~/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
            
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports-${{ strategy.job-index }}
          path: TestResults-${{ strategy.job-index }}.xcresult

  build:
    needs: [lint, test]
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
          
      - name: Cache derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ matrix.configuration }}-${{ hashFiles('**/*.xcodeproj') }}
          restore-keys: |
            ${{ runner.os }}-derived-data-${{ matrix.configuration }}-
            ${{ runner.os }}-derived-data-
            
      - name: Build for iOS Simulator
        run: |
          set -o pipefail
          xcodebuild clean build \
            -project ${{ env.PROJECT_NAME }}.xcodeproj \
            -scheme ${{ env.SCHEME_NAME }} \
            -configuration ${{ matrix.configuration }} \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.1" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            | xcpretty
            
