name: swift ci

on:
 push:
  branches: [ "main", "dev", "qa" ]
 pull_request:
  branches: [ "main", "dev", "qa", "feature/*", "release/*" ]

jobs:
 lint:
  runs-on: macos-latest

  steps:
   - name: checkout the code
     uses: actions/checkout@v4

   - name: install swiftlint
     run: brew install swiftlint

   - name: run swiftlint
     run: swiftlint 


 unit-test:
   needs: lint
   runs-on: macos-latest

   steps:
    - name: checkout the code
      uses: actions/checkout@v4
  
    - name: Run Tests
      run: |
          xcodebuild test \
            -project build-test-ios.xcodeproj \
            -scheme build-test-ios \
            -destination 'platform=iOS Simulator,name=iPhone 14'

 build:
  needs: [lint, unit-test]
  runs-on: macos-latest

  steps:
   - name: checkout the code
     uses: actions/checkout@v4

   - name: Select Xcode Version
     run: sudo xcode-select -s /Applications/Xcode_15.4.app

   - name: built the swift code
     run: |
          xcodebuild clean build \
            -project build-test-ios.xcodeproj \
            -scheme build-test-ios \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.4"
        
