name: swift ci

on:
 push:
  branches: [ "main", "dev", "qa" ]
 pull_request:
  branches: [ "main", "dev", "qa", "feature/*", "release/*" ]

jobs:
 lint:
  runs-on: macos-latest

  steps:
   - name: checkout the code
     uses: actions/checkout@v4

   - name: install swiftlint
     run: brew install swiftlint

   - name: run swiftlint
     run: swiftlint 


 test:
    needs: [lint]
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode 16
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1.0'
        
    - name: Build and Test
      run: |
        xcodebuild test \
          -project build-test-ios.xcodeproj \
          -scheme build-test-ios \
          -resultBundlePath TestResults \
          -destination "platform=iOS Simulator,name=iPad (10th generation),OS=18.1" \
          CODE_SIGNING_REQUIRED=NO
          CODE_SIGNING_ALLOWED=NO
          
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults.xcresult

 build:
  needs: [lint, test]
  runs-on: macos-latest

  steps:
   - name: checkout the code
     uses: actions/checkout@v4

   - name: Setup Xcode 16
     uses: maxim-lobanov/setup-xcode@v1
     with:
        xcode-version: '16.1.0'

   - name: Build the Swift code
     run: |
       xcodebuild clean build \
       -project build-test-ios.xcodeproj \
       -scheme build-test-ios \
       -destination "id=8A897D71-AFE1-42FF-B5F4-0F08ADED6B1B"
